### PR TITLE
Ks empty list

### LINKED ISSUE #49: Style empty shopping list page

### PR DESCRIPTION
**Pull request by ksiman14**
## Description

- Created full shopping basket image to match our empty basket from Figma
- Empty basket displays when shopping list is empty
- Full basket displays when shopping list contains items
- Removed unused images from `public/img` folder

## Related Issue

closes #49 

## Acceptance Criteria

- [x] Add style to list view when there are no items in the list

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓ | :sparkles: New feature     |

### Before

Screen Shot 2021-09-01 at 7 32 20 AM

Screen Shot 2021-09-01 at 7 31 42 AM

### After

Screen Shot 2021-09-01 at 7 28 59 AM

Screen Shot 2021-09-01 at 7 30 26 AM

## Testing Steps / QA Criteria

- checkout `ks-empty-list` branch or visit preview url
- create a list with no items, you should see an empty basket in the list view
- add items to your list, you should see a full basket in the list view

### CODE REVIEW

**Review by sandaiiyahh — APPROVED** [review]
Omg, the full basket and without is such a cute touch!! I love it. Did you make the full basket yourself? :D

**Comment by ksiman14** [comment]
> Omg, the full basket and without is such a cute touch!! I love it. Did you make the full basket yourself? :D

Yes, I used Canva!

**Review by hulyak — APPROVED** [review]
It looks pretty cool, Kelsey. I liked your idea about showing an empty basket to users, and the images look better.

**Comment by isaabutaa** [comment]
This is awesome, @ksiman14! The baskets are fabulous and take the styling of the app to a whole new level. 🥇

**Review by isaabutaa — APPROVED** [review]

**Pull request merged**
